/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardAdvisorRouteImport } from './routes/dashboard/advisor'
import { Route as DashboardCalculatorRouteImport } from './routes/dashboard/calculator'
import { Route as DashboardCalendarRouteImport } from './routes/dashboard/calendar'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard/documents'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardAdvisorRoute = DashboardAdvisorRouteImport.update({
  id: '/advisor',
  path: '/advisor',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalculatorRoute = DashboardCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCalendarRoute = DashboardCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calculator': typeof CalculatorRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/documents': typeof DocumentsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/advisor': typeof DashboardAdvisorRoute
  '/dashboard/calculator': typeof DashboardCalculatorRoute
  '/dashboard/calendar': typeof DashboardCalendarRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/login'
    | '/signup'
    | '/dashboard/advisor'
    | '/dashboard/calculator'
    | '/dashboard/calendar'
    | '/dashboard/documents'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calculator'
    | '/documents'
    | '/help'
    | '/login'
    | '/signup'
    | '/dashboard/advisor'
    | '/dashboard/calculator'
    | '/dashboard/calendar'
    | '/dashboard/documents'
    | '/dashboard/profile'
    | '/dashboard'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/calculator'
    | '/dashboard'
    | '/documents'
    | '/help'
    | '/login'
    | '/signup'
    | '/dashboard/advisor'
    | '/dashboard/calculator'
    | '/dashboard/calendar'
    | '/dashboard/documents'
    | '/dashboard/profile'
    | '/dashboard/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalculatorRoute: typeof CalculatorRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DocumentsRoute: typeof DocumentsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/advisor': {
      id: '/dashboard/advisor'
      path: '/advisor'
      fullPath: '/dashboard/advisor'
      preLoaderRoute: typeof DashboardAdvisorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calculator': {
      id: '/dashboard/calculator'
      path: '/calculator'
      fullPath: '/dashboard/calculator'
      preLoaderRoute: typeof DashboardCalculatorRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/calendar': {
      id: '/dashboard/calendar'
      path: '/calendar'
      fullPath: '/dashboard/calendar'
      preLoaderRoute: typeof DashboardCalendarRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardRouteChildren {
  DashboardAdvisorRoute: typeof DashboardAdvisorRoute
  DashboardCalculatorRoute: typeof DashboardCalculatorRoute
  DashboardCalendarRoute: typeof DashboardCalendarRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardAdvisorRoute: DashboardAdvisorRoute,
  DashboardCalculatorRoute: DashboardCalculatorRoute,
  DashboardCalendarRoute: DashboardCalendarRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalculatorRoute: CalculatorRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DocumentsRoute: DocumentsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
